##### Copyright 2019 The TensorFlow Authors.

Licensed under the Apache License, Version 2.0 (the "License");

In [1]:
#@title Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Load a pandas.DataFrame

<table class="tfo-notebook-buttons" align="left">
  <td>
    <a target="_blank" href="https://www.tensorflow.org/tutorials/load_data/pandas_dataframe"><img src="https://www.tensorflow.org/images/tf_logo_32px.png" />View on TensorFlow.org</a>
  </td>
  <td>
    <a target="_blank" href="https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/load_data/pandas_dataframe.ipynb"><img src="https://www.tensorflow.org/images/colab_logo_32px.png" />Run in Google Colab</a>
  </td>
  <td>
    <a target="_blank" href="https://github.com/tensorflow/docs/blob/master/site/en/tutorials/load_data/pandas_dataframe.ipynb"><img src="https://www.tensorflow.org/images/GitHub-Mark-32px.png" />View source on GitHub</a>
  </td>
  <td>
    <a href="https://storage.googleapis.com/tensorflow_docs/docs/site/en/tutorials/load_data/pandas_dataframe.ipynb"><img src="https://www.tensorflow.org/images/download_logo_32px.png" />Download notebook</a>
  </td>
</table>

This tutorial provides an example of how to load pandas dataframes into a `tf.data.Dataset`.

This tutorials uses a small [dataset](https://archive.ics.uci.edu/ml/datasets/heart+Disease) provided by the Cleveland Clinic Foundation for Heart Disease. There are several hundred rows in the CSV. Each row describes a patient, and each column describes an attribute. We will use this information to predict whether a patient has heart disease, which in this dataset is a binary classification task.

## Read data using pandas

In [2]:
import pandas as pd
import tensorflow as tf

Download the csv file containing the heart dataset.

In [3]:
csv_file = tf.keras.utils.get_file('heart.csv', 'https://storage.googleapis.com/download.tensorflow.org/data/heart.csv')

 8192/13273 [=================>............] - ETA: 0s

16384/13273 [=====================================] - 0s 0us/step


Read the csv file using pandas.

In [4]:
df = pd.read_csv(csv_file)

In [5]:
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   1       145   233    1        2      150      0      2.3      3   
1   67    1   4       160   286    0        2      108      1      1.5      2   
2   67    1   4       120   229    0        2      129      1      2.6      2   
3   37    1   3       130   250    0        0      187      0      3.5      3   
4   41    0   2       130   204    0        2      172      0      1.4      1   

   ca        thal  target  
0   0       fixed       0  
1   3      normal       1  
2   2  reversible       0  
3   0      normal       0  
4   0      normal       0

In [6]:
df.dtypes

age           int64
sex           int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal         object
target        int64
dtype: object

Convert `thal` column which is an `object` in the dataframe to a discrete numerical value.

In [7]:
df['thal'] = pd.Categorical(df['thal'])
df['thal'] = df.thal.cat.codes

In [8]:
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   1       145   233    1        2      150      0      2.3      3   
1   67    1   4       160   286    0        2      108      1      1.5      2   
2   67    1   4       120   229    0        2      129      1      2.6      2   
3   37    1   3       130   250    0        0      187      0      3.5      3   
4   41    0   2       130   204    0        2      172      0      1.4      1   

   ca  thal  target  
0   0     2       0  
1   3     3       1  
2   2     4       0  
3   0     3       0  
4   0     3       0

## Load data using `tf.data.Dataset`

Use `tf.data.Dataset.from_tensor_slices` to read the values from a pandas dataframe. 

One of the advantages of using `tf.data.Dataset` is it allows you to write simple, highly efficient data pipelines. Read the [loading data guide](https://www.tensorflow.org/guide/data) to find out more.

In [9]:
target = df.pop('target')

In [10]:
dataset = tf.data.Dataset.from_tensor_slices((df.values, target.values))

In [11]:
for feat, targ in dataset.take(5):
  print ('Features: {}, Target: {}'.format(feat, targ))

Features: [ 63.    1.    1.  145.  233.    1.    2.  150.    0.    2.3   3.    0.
   2. ], Target: 0
Features: [ 67.    1.    4.  160.  286.    0.    2.  108.    1.    1.5   2.    3.
   3. ], Target: 1
Features: [ 67.    1.    4.  120.  229.    0.    2.  129.    1.    2.6   2.    2.
   4. ], Target: 0
Features: [ 37.    1.    3.  130.  250.    0.    0.  187.    0.    3.5   3.    0.
   3. ], Target: 0
Features: [ 41.    0.    2.  130.  204.    0.    2.  172.    0.    1.4   1.    0.
   3. ], Target: 0


Since a `pd.Series` implements the `__array__` protocol it can be used transparently nearly anywhere you would use a `np.array` or a `tf.Tensor`.

In [12]:
tf.constant(df['thal'])

<tf.Tensor: shape=(303,), dtype=int8, numpy=
array([2, 3, 4, 3, 3, 3, 3, 3, 4, 4, 2, 3, 2, 4, 4, 3, 4, 3, 3, 3, 3, 3,
       3, 4, 4, 3, 3, 3, 3, 4, 3, 4, 3, 4, 3, 3, 4, 2, 4, 3, 4, 3, 4, 4,
       2, 3, 3, 4, 3, 3, 4, 3, 3, 3, 4, 3, 3, 3, 3, 3, 3, 4, 4, 3, 3, 4,
       4, 2, 3, 3, 4, 3, 4, 3, 3, 4, 4, 3, 3, 4, 4, 3, 3, 3, 3, 4, 4, 4,
       3, 3, 4, 3, 4, 4, 3, 4, 3, 3, 3, 4, 3, 4, 4, 3, 3, 4, 4, 4, 4, 4,
       3, 3, 3, 3, 4, 3, 4, 3, 4, 4, 3, 3, 2, 4, 4, 2, 3, 3, 4, 4, 3, 4,
       3, 3, 4, 2, 4, 4, 3, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4,
       4, 3, 3, 3, 4, 3, 4, 3, 4, 3, 3, 3, 3, 3, 3, 3, 4, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 4, 4, 3, 3, 3, 3, 3, 3, 3, 3, 4, 3, 4, 3, 2,
       4, 4, 3, 3, 3, 3, 3, 3, 4, 3, 3, 3, 3, 3, 2, 2, 4, 3, 4, 2, 4, 3,
       3, 4, 3, 3, 3, 3, 4, 3, 4, 3, 4, 2, 2, 4, 3, 4, 3, 2, 4, 3, 3, 2,
       4, 4, 4, 4, 3, 0, 3, 3, 3, 3, 1, 4, 3, 3, 3, 4, 3, 4, 3, 3, 3, 4,
       3, 3, 4, 4, 4, 4, 3, 3, 4, 3, 4, 3, 4, 4, 3, 4, 4, 3, 4, 4, 3, 3,
      

Shuffle and batch the dataset.

In [13]:
train_dataset = dataset.shuffle(len(df)).batch(1)

## Create and train a model

In [14]:
def get_compiled_model():
  model = tf.keras.Sequential([
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(1)
  ])

  model.compile(optimizer='adam',
                loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
                metrics=['accuracy'])
  return model

In [15]:
model = get_compiled_model()
model.fit(train_dataset, epochs=15)

Epoch 1/15


  1/303 [..............................] - ETA: 3:55 - loss: 4.2778e-05 - accuracy: 1.0000

 26/303 [=>............................] - ETA: 0s - loss: 3.0096 - accuracy: 0.4615      

 53/303 [====>.........................] - ETA: 0s - loss: 2.2392 - accuracy: 0.6038

 80/303 [======>.......................] - ETA: 0s - loss: 2.6054 - accuracy: 0.6375

106/303 [=========>....................] - ETA: 0s - loss: 2.5147 - accuracy: 0.6415

133/303 [============>.................] - ETA: 0s - loss: 2.4209 - accuracy: 0.6767

160/303 [==============>...............] - ETA: 0s - loss: 2.2450 - accuracy: 0.6812

186/303 [=================>............] - ETA: 0s - loss: 2.2348 - accuracy: 0.6613

212/303 [===================>..........] - ETA: 0s - loss: 2.0847 - accuracy: 0.6651

239/303 [======================>.......] - ETA: 0s - loss: 1.9133 - accuracy: 0.6820

266/303 [=========================>....] - ETA: 0s - loss: 1.8593 - accuracy: 0.6692

293/303 [============================>.] - ETA: 0s - loss: 1.8013 - accuracy: 0.6689

303/303 [==============================] - 1s 2ms/step - loss: 1.8207 - accuracy: 0.6667


Epoch 2/15
  1/303 [..............................] - ETA: 0s - loss: 0.0013 - accuracy: 1.0000

 28/303 [=>............................] - ETA: 0s - loss: 0.4955 - accuracy: 0.8929

 55/303 [====>.........................] - ETA: 0s - loss: 1.2822 - accuracy: 0.7455

 82/303 [=======>......................] - ETA: 0s - loss: 1.0875 - accuracy: 0.7317

109/303 [=========>....................] - ETA: 0s - loss: 0.9804 - accuracy: 0.7339

136/303 [============>.................] - ETA: 0s - loss: 1.1357 - accuracy: 0.7353

163/303 [===============>..............] - ETA: 0s - loss: 1.0088 - accuracy: 0.7607

190/303 [=================>............] - ETA: 0s - loss: 1.1751 - accuracy: 0.7158

217/303 [====================>.........] - ETA: 0s - loss: 1.0818 - accuracy: 0.7281

244/303 [=======================>......] - ETA: 0s - loss: 1.1478 - accuracy: 0.7008

271/303 [=========================>....] - ETA: 0s - loss: 1.1624 - accuracy: 0.6974

298/303 [============================>.] - ETA: 0s - loss: 1.1141 - accuracy: 0.7114

303/303 [==============================] - 1s 2ms/step - loss: 1.1188 - accuracy: 0.7129


Epoch 3/15
  1/303 [..............................] - ETA: 0s - loss: 6.4809 - accuracy: 0.0000e+00

 28/303 [=>............................] - ETA: 0s - loss: 1.3127 - accuracy: 0.6071    

 55/303 [====>.........................] - ETA: 0s - loss: 1.3240 - accuracy: 0.6000

 82/303 [=======>......................] - ETA: 0s - loss: 1.0440 - accuracy: 0.6829

109/303 [=========>....................] - ETA: 0s - loss: 0.9646 - accuracy: 0.6972

136/303 [============>.................] - ETA: 0s - loss: 1.0105 - accuracy: 0.6838

164/303 [===============>..............] - ETA: 0s - loss: 0.9942 - accuracy: 0.6951

191/303 [=================>............] - ETA: 0s - loss: 0.9912 - accuracy: 0.6806

219/303 [====================>.........] - ETA: 0s - loss: 0.9993 - accuracy: 0.6758

246/303 [=======================>......] - ETA: 0s - loss: 0.9644 - accuracy: 0.6911

273/303 [==========================>...] - ETA: 0s - loss: 0.9526 - accuracy: 0.6996

301/303 [============================>.] - ETA: 0s - loss: 1.0087 - accuracy: 0.6910

303/303 [==============================] - 1s 2ms/step - loss: 1.0034 - accuracy: 0.6931


Epoch 4/15
  1/303 [..............................] - ETA: 0s - loss: 3.5312 - accuracy: 0.0000e+00

 28/303 [=>............................] - ETA: 0s - loss: 1.0522 - accuracy: 0.7143    

 54/303 [====>.........................] - ETA: 0s - loss: 0.8317 - accuracy: 0.7222

 81/303 [=======>......................] - ETA: 0s - loss: 0.7307 - accuracy: 0.7407

108/303 [=========>....................] - ETA: 0s - loss: 0.7723 - accuracy: 0.7130

135/303 [============>.................] - ETA: 0s - loss: 0.7341 - accuracy: 0.7259

162/303 [===============>..............] - ETA: 0s - loss: 0.7112 - accuracy: 0.7284

189/303 [=================>............] - ETA: 0s - loss: 0.6895 - accuracy: 0.7407

217/303 [====================>.........] - ETA: 0s - loss: 0.7375 - accuracy: 0.7281

244/303 [=======================>......] - ETA: 0s - loss: 0.7714 - accuracy: 0.7213

272/303 [=========================>....] - ETA: 0s - loss: 0.7431 - accuracy: 0.7316

299/303 [============================>.] - ETA: 0s - loss: 0.7925 - accuracy: 0.7157

303/303 [==============================] - 1s 2ms/step - loss: 0.7867 - accuracy: 0.7162


Epoch 5/15
  1/303 [..............................] - ETA: 0s - loss: 3.3470 - accuracy: 0.0000e+00

 28/303 [=>............................] - ETA: 0s - loss: 0.8218 - accuracy: 0.6786    

 55/303 [====>.........................] - ETA: 0s - loss: 0.7380 - accuracy: 0.6909

 82/303 [=======>......................] - ETA: 0s - loss: 0.8305 - accuracy: 0.6829

109/303 [=========>....................] - ETA: 0s - loss: 0.8113 - accuracy: 0.6789

136/303 [============>.................] - ETA: 0s - loss: 0.7613 - accuracy: 0.6985

163/303 [===============>..............] - ETA: 0s - loss: 0.6828 - accuracy: 0.7301

190/303 [=================>............] - ETA: 0s - loss: 0.7578 - accuracy: 0.7053

216/303 [====================>.........] - ETA: 0s - loss: 0.7506 - accuracy: 0.7083

243/303 [=======================>......] - ETA: 0s - loss: 0.7731 - accuracy: 0.6955

270/303 [=========================>....] - ETA: 0s - loss: 0.7187 - accuracy: 0.7148

296/303 [============================>.] - ETA: 0s - loss: 0.7348 - accuracy: 0.7061

303/303 [==============================] - 1s 2ms/step - loss: 0.7202 - accuracy: 0.7129


Epoch 6/15
  1/303 [..............................] - ETA: 0s - loss: 0.0231 - accuracy: 1.0000

 28/303 [=>............................] - ETA: 0s - loss: 0.3929 - accuracy: 0.8214

 55/303 [====>.........................] - ETA: 0s - loss: 0.5547 - accuracy: 0.8000

 82/303 [=======>......................] - ETA: 0s - loss: 0.5285 - accuracy: 0.7805

107/303 [=========>....................] - ETA: 0s - loss: 0.5717 - accuracy: 0.7477

131/303 [===========>..................] - ETA: 0s - loss: 0.5982 - accuracy: 0.7405

156/303 [==============>...............] - ETA: 0s - loss: 0.6224 - accuracy: 0.7308

182/303 [=================>............] - ETA: 0s - loss: 0.6473 - accuracy: 0.7363

207/303 [===================>..........] - ETA: 0s - loss: 0.6157 - accuracy: 0.7488

232/303 [=====================>........] - ETA: 0s - loss: 0.5972 - accuracy: 0.7586

258/303 [========================>.....] - ETA: 0s - loss: 0.6412 - accuracy: 0.7364

285/303 [===========================>..] - ETA: 0s - loss: 0.6395 - accuracy: 0.7333

303/303 [==============================] - 1s 2ms/step - loss: 0.6262 - accuracy: 0.7393


Epoch 7/15
  1/303 [..............................] - ETA: 0s - loss: 1.5283 - accuracy: 0.0000e+00

 28/303 [=>............................] - ETA: 0s - loss: 0.5023 - accuracy: 0.7500    

 55/303 [====>.........................] - ETA: 0s - loss: 0.4326 - accuracy: 0.8000

 83/303 [=======>......................] - ETA: 0s - loss: 0.4427 - accuracy: 0.7831

110/303 [=========>....................] - ETA: 0s - loss: 0.4715 - accuracy: 0.7818

137/303 [============>.................] - ETA: 0s - loss: 0.5181 - accuracy: 0.7737

164/303 [===============>..............] - ETA: 0s - loss: 0.5865 - accuracy: 0.7683

191/303 [=================>............] - ETA: 0s - loss: 0.6089 - accuracy: 0.7539

218/303 [====================>.........] - ETA: 0s - loss: 0.6623 - accuracy: 0.7294

245/303 [=======================>......] - ETA: 0s - loss: 0.6671 - accuracy: 0.7184

273/303 [==========================>...] - ETA: 0s - loss: 0.6643 - accuracy: 0.7216

300/303 [============================>.] - ETA: 0s - loss: 0.6757 - accuracy: 0.7100

303/303 [==============================] - 1s 2ms/step - loss: 0.6705 - accuracy: 0.7129


Epoch 8/15
  1/303 [..............................] - ETA: 0s - loss: 0.5489 - accuracy: 1.0000

 28/303 [=>............................] - ETA: 0s - loss: 0.6371 - accuracy: 0.8571

 55/303 [====>.........................] - ETA: 0s - loss: 0.5134 - accuracy: 0.8182

 82/303 [=======>......................] - ETA: 0s - loss: 0.5263 - accuracy: 0.7927

108/303 [=========>....................] - ETA: 0s - loss: 0.4875 - accuracy: 0.8056

133/303 [============>.................] - ETA: 0s - loss: 0.4983 - accuracy: 0.7970

158/303 [==============>...............] - ETA: 0s - loss: 0.5403 - accuracy: 0.7848

184/303 [=================>............] - ETA: 0s - loss: 0.5574 - accuracy: 0.7663

211/303 [===================>..........] - ETA: 0s - loss: 0.5507 - accuracy: 0.7725

238/303 [======================>.......] - ETA: 0s - loss: 0.5592 - accuracy: 0.7605

265/303 [=========================>....] - ETA: 0s - loss: 0.5706 - accuracy: 0.7509

292/303 [===========================>..] - ETA: 0s - loss: 0.5618 - accuracy: 0.7603

303/303 [==============================] - 1s 2ms/step - loss: 0.5652 - accuracy: 0.7591


Epoch 9/15
  1/303 [..............................] - ETA: 0s - loss: 2.3763 - accuracy: 0.0000e+00

 28/303 [=>............................] - ETA: 0s - loss: 0.4511 - accuracy: 0.7857    

 56/303 [====>.........................] - ETA: 0s - loss: 0.6059 - accuracy: 0.7679

 83/303 [=======>......................] - ETA: 0s - loss: 0.6370 - accuracy: 0.7470

111/303 [=========>....................] - ETA: 0s - loss: 0.6158 - accuracy: 0.7477

138/303 [============>.................] - ETA: 0s - loss: 0.5909 - accuracy: 0.7391

165/303 [===============>..............] - ETA: 0s - loss: 0.5273 - accuracy: 0.7636

192/303 [==================>...........] - ETA: 0s - loss: 0.5195 - accuracy: 0.7552

219/303 [====================>.........] - ETA: 0s - loss: 0.5361 - accuracy: 0.7534

246/303 [=======================>......] - ETA: 0s - loss: 0.5174 - accuracy: 0.7683

273/303 [==========================>...] - ETA: 0s - loss: 0.5221 - accuracy: 0.7619

301/303 [============================>.] - ETA: 0s - loss: 0.5241 - accuracy: 0.7641

303/303 [==============================] - 1s 2ms/step - loss: 0.5216 - accuracy: 0.7657


Epoch 10/15
  1/303 [..............................] - ETA: 0s - loss: 0.5833 - accuracy: 1.0000

 28/303 [=>............................] - ETA: 0s - loss: 0.6903 - accuracy: 0.7500

 56/303 [====>.........................] - ETA: 0s - loss: 0.6854 - accuracy: 0.7500

 82/303 [=======>......................] - ETA: 0s - loss: 0.6770 - accuracy: 0.7317

109/303 [=========>....................] - ETA: 0s - loss: 0.6393 - accuracy: 0.7248

136/303 [============>.................] - ETA: 0s - loss: 0.5693 - accuracy: 0.7574

163/303 [===============>..............] - ETA: 0s - loss: 0.5415 - accuracy: 0.7607

191/303 [=================>............] - ETA: 0s - loss: 0.5627 - accuracy: 0.7435

218/303 [====================>.........] - ETA: 0s - loss: 0.5705 - accuracy: 0.7431

243/303 [=======================>......] - ETA: 0s - loss: 0.5784 - accuracy: 0.7449

270/303 [=========================>....] - ETA: 0s - loss: 0.5630 - accuracy: 0.7444

297/303 [============================>.] - ETA: 0s - loss: 0.5478 - accuracy: 0.7508

303/303 [==============================] - 1s 2ms/step - loss: 0.5485 - accuracy: 0.7492


Epoch 11/15
  1/303 [..............................] - ETA: 0s - loss: 1.9207 - accuracy: 0.0000e+00

 28/303 [=>............................] - ETA: 0s - loss: 0.4535 - accuracy: 0.7857    

 55/303 [====>.........................] - ETA: 0s - loss: 0.4360 - accuracy: 0.8182

 82/303 [=======>......................] - ETA: 0s - loss: 0.4863 - accuracy: 0.8171

109/303 [=========>....................] - ETA: 0s - loss: 0.5144 - accuracy: 0.7982

136/303 [============>.................] - ETA: 0s - loss: 0.4987 - accuracy: 0.7868

163/303 [===============>..............] - ETA: 0s - loss: 0.5073 - accuracy: 0.7853

190/303 [=================>............] - ETA: 0s - loss: 0.5183 - accuracy: 0.7737

218/303 [====================>.........] - ETA: 0s - loss: 0.5050 - accuracy: 0.7798

245/303 [=======================>......] - ETA: 0s - loss: 0.5143 - accuracy: 0.7796

272/303 [=========================>....] - ETA: 0s - loss: 0.5130 - accuracy: 0.7868

299/303 [============================>.] - ETA: 0s - loss: 0.5062 - accuracy: 0.7826

303/303 [==============================] - 1s 2ms/step - loss: 0.5086 - accuracy: 0.7822


Epoch 12/15
  1/303 [..............................] - ETA: 0s - loss: 0.4614 - accuracy: 1.0000

 28/303 [=>............................] - ETA: 0s - loss: 0.3887 - accuracy: 0.8571

 55/303 [====>.........................] - ETA: 0s - loss: 0.4766 - accuracy: 0.7818

 83/303 [=======>......................] - ETA: 0s - loss: 0.4351 - accuracy: 0.7831

110/303 [=========>....................] - ETA: 0s - loss: 0.4774 - accuracy: 0.7545

137/303 [============>.................] - ETA: 0s - loss: 0.4473 - accuracy: 0.7591

163/303 [===============>..............] - ETA: 0s - loss: 0.4667 - accuracy: 0.7607

191/303 [=================>............] - ETA: 0s - loss: 0.4562 - accuracy: 0.7644

218/303 [====================>.........] - ETA: 0s - loss: 0.4783 - accuracy: 0.7569

245/303 [=======================>......] - ETA: 0s - loss: 0.4744 - accuracy: 0.7592

273/303 [==========================>...] - ETA: 0s - loss: 0.4597 - accuracy: 0.7656

300/303 [============================>.] - ETA: 0s - loss: 0.4730 - accuracy: 0.7567

303/303 [==============================] - 1s 2ms/step - loss: 0.4725 - accuracy: 0.7591


Epoch 13/15
  1/303 [..............................] - ETA: 0s - loss: 0.0220 - accuracy: 1.0000

 27/303 [=>............................] - ETA: 0s - loss: 0.3363 - accuracy: 0.8148

 53/303 [====>.........................] - ETA: 0s - loss: 0.3750 - accuracy: 0.8113

 78/303 [======>.......................] - ETA: 0s - loss: 0.4505 - accuracy: 0.7949

105/303 [=========>....................] - ETA: 0s - loss: 0.4863 - accuracy: 0.8095

132/303 [============>.................] - ETA: 0s - loss: 0.4839 - accuracy: 0.8106

159/303 [==============>...............] - ETA: 0s - loss: 0.4764 - accuracy: 0.8113

185/303 [=================>............] - ETA: 0s - loss: 0.4997 - accuracy: 0.7892

212/303 [===================>..........] - ETA: 0s - loss: 0.5096 - accuracy: 0.7736

239/303 [======================>.......] - ETA: 0s - loss: 0.5193 - accuracy: 0.7615

266/303 [=========================>....] - ETA: 0s - loss: 0.5168 - accuracy: 0.7669

293/303 [============================>.] - ETA: 0s - loss: 0.5064 - accuracy: 0.7713

303/303 [==============================] - 1s 2ms/step - loss: 0.5027 - accuracy: 0.7690


Epoch 14/15
  1/303 [..............................] - ETA: 0s - loss: 0.0317 - accuracy: 1.0000

 28/303 [=>............................] - ETA: 0s - loss: 0.2644 - accuracy: 0.8929

 54/303 [====>.........................] - ETA: 0s - loss: 0.3415 - accuracy: 0.8333

 80/303 [======>.......................] - ETA: 0s - loss: 0.4192 - accuracy: 0.8000

107/303 [=========>....................] - ETA: 0s - loss: 0.4299 - accuracy: 0.7850

134/303 [============>.................] - ETA: 0s - loss: 0.4366 - accuracy: 0.7910

160/303 [==============>...............] - ETA: 0s - loss: 0.4488 - accuracy: 0.8125

187/303 [=================>............] - ETA: 0s - loss: 0.5061 - accuracy: 0.7861

214/303 [====================>.........] - ETA: 0s - loss: 0.5030 - accuracy: 0.7897

241/303 [======================>.......] - ETA: 0s - loss: 0.5369 - accuracy: 0.7718

267/303 [=========================>....] - ETA: 0s - loss: 0.5260 - accuracy: 0.7603

294/303 [============================>.] - ETA: 0s - loss: 0.5105 - accuracy: 0.7687

303/303 [==============================] - 1s 2ms/step - loss: 0.5118 - accuracy: 0.7690


Epoch 15/15
  1/303 [..............................] - ETA: 0s - loss: 0.1396 - accuracy: 1.0000

 27/303 [=>............................] - ETA: 0s - loss: 0.5041 - accuracy: 0.7037

 54/303 [====>.........................] - ETA: 0s - loss: 0.4951 - accuracy: 0.7593

 81/303 [=======>......................] - ETA: 0s - loss: 0.4503 - accuracy: 0.7901

108/303 [=========>....................] - ETA: 0s - loss: 0.4351 - accuracy: 0.8056

135/303 [============>.................] - ETA: 0s - loss: 0.4362 - accuracy: 0.8074

162/303 [===============>..............] - ETA: 0s - loss: 0.4606 - accuracy: 0.7963

187/303 [=================>............] - ETA: 0s - loss: 0.4978 - accuracy: 0.7861

212/303 [===================>..........] - ETA: 0s - loss: 0.4870 - accuracy: 0.7830

236/303 [======================>.......] - ETA: 0s - loss: 0.4805 - accuracy: 0.7924

260/303 [========================>.....] - ETA: 0s - loss: 0.4597 - accuracy: 0.7962

285/303 [===========================>..] - ETA: 0s - loss: 0.4660 - accuracy: 0.7930

303/303 [==============================] - 1s 2ms/step - loss: 0.4671 - accuracy: 0.7954


## Alternative to feature columns

Passing a dictionary as an input to a model is as easy as creating a matching dictionary of `tf.keras.layers.Input` layers, applying any pre-processing and stacking them up using the [functional api](../../guide/keras/functional.ipynb). You can use this as an alternative to [feature columns](../keras/feature_columns.ipynb).

In [16]:
inputs = {key: tf.keras.layers.Input(shape=(), name=key) for key in df.keys()}
x = tf.stack(list(inputs.values()), axis=-1)

x = tf.keras.layers.Dense(10, activation='relu')(x)
output = tf.keras.layers.Dense(1)(x)

model_func = tf.keras.Model(inputs=inputs, outputs=output)

model_func.compile(optimizer='adam',
                   loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
                   metrics=['accuracy'])

The easiest way to preserve the column structure of a `pd.DataFrame` when used with `tf.data` is to convert the `pd.DataFrame` to a `dict`, and slice that dictionary.

In [17]:
dict_slices = tf.data.Dataset.from_tensor_slices((df.to_dict('list'), target.values)).batch(16)

In [18]:
for dict_slice in dict_slices.take(1):
  print (dict_slice)

({'age': <tf.Tensor: shape=(16,), dtype=int32, numpy=
array([63, 67, 67, 37, 41, 56, 62, 57, 63, 53, 57, 56, 56, 44, 52, 57],
      dtype=int32)>, 'sex': <tf.Tensor: shape=(16,), dtype=int32, numpy=array([1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1], dtype=int32)>, 'cp': <tf.Tensor: shape=(16,), dtype=int32, numpy=array([1, 4, 4, 3, 2, 2, 4, 4, 4, 4, 4, 2, 3, 2, 3, 3], dtype=int32)>, 'trestbps': <tf.Tensor: shape=(16,), dtype=int32, numpy=
array([145, 160, 120, 130, 130, 120, 140, 120, 130, 140, 140, 140, 130,
       120, 172, 150], dtype=int32)>, 'chol': <tf.Tensor: shape=(16,), dtype=int32, numpy=
array([233, 286, 229, 250, 204, 236, 268, 354, 254, 203, 192, 294, 256,
       263, 199, 168], dtype=int32)>, 'fbs': <tf.Tensor: shape=(16,), dtype=int32, numpy=array([1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0], dtype=int32)>, 'restecg': <tf.Tensor: shape=(16,), dtype=int32, numpy=array([2, 2, 2, 0, 2, 0, 2, 0, 2, 2, 0, 2, 2, 0, 0, 0], dtype=int32)>, 'thalach': <tf.Tensor: shape=(16

In [19]:
model_func.fit(dict_slices, epochs=15)

Epoch 1/15


 1/19 [>.............................] - ETA: 6s - loss: 18.4443 - accuracy: 0.2500

19/19 [==============================] - 0s 3ms/step - loss: 10.4752 - accuracy: 0.2640


Epoch 2/15
 1/19 [>.............................] - ETA: 0s - loss: 4.8812 - accuracy: 0.2500

19/19 [==============================] - 0s 3ms/step - loss: 3.6499 - accuracy: 0.5380


Epoch 3/15
 1/19 [>.............................] - ETA: 0s - loss: 3.5328 - accuracy: 0.5000

19/19 [==============================] - 0s 3ms/step - loss: 3.3146 - accuracy: 0.5875


Epoch 4/15
 1/19 [>.............................] - ETA: 0s - loss: 3.4291 - accuracy: 0.3750

19/19 [==============================] - 0s 3ms/step - loss: 3.0684 - accuracy: 0.4983


Epoch 5/15
 1/19 [>.............................] - ETA: 0s - loss: 3.2296 - accuracy: 0.3750

19/19 [==============================] - 0s 3ms/step - loss: 2.8597 - accuracy: 0.5380


Epoch 6/15
 1/19 [>.............................] - ETA: 0s - loss: 2.9399 - accuracy: 0.3750

19/19 [==============================] - 0s 3ms/step - loss: 2.6409 - accuracy: 0.5281


Epoch 7/15
 1/19 [>.............................] - ETA: 0s - loss: 2.7088 - accuracy: 0.3750

19/19 [==============================] - 0s 3ms/step - loss: 2.4251 - accuracy: 0.5347


Epoch 8/15
 1/19 [>.............................] - ETA: 0s - loss: 2.4499 - accuracy: 0.3750

19/19 [==============================] - 0s 3ms/step - loss: 2.2034 - accuracy: 0.5347


Epoch 9/15
 1/19 [>.............................] - ETA: 0s - loss: 2.1958 - accuracy: 0.3750

19/19 [==============================] - 0s 3ms/step - loss: 1.9842 - accuracy: 0.5413


Epoch 10/15
 1/19 [>.............................] - ETA: 0s - loss: 1.9355 - accuracy: 0.3750

19/19 [==============================] - 0s 3ms/step - loss: 1.7686 - accuracy: 0.5545


Epoch 11/15
 1/19 [>.............................] - ETA: 0s - loss: 1.6621 - accuracy: 0.3750

19/19 [==============================] - 0s 3ms/step - loss: 1.5605 - accuracy: 0.5677


Epoch 12/15
 1/19 [>.............................] - ETA: 0s - loss: 1.3957 - accuracy: 0.4375

19/19 [==============================] - 0s 3ms/step - loss: 1.3677 - accuracy: 0.5644


Epoch 13/15
 1/19 [>.............................] - ETA: 0s - loss: 1.1514 - accuracy: 0.4375

19/19 [==============================] - ETA: 0s - loss: 1.1975 - accuracy: 0.5875

19/19 [==============================] - 0s 3ms/step - loss: 1.1975 - accuracy: 0.5875


Epoch 14/15
 1/19 [>.............................] - ETA: 0s - loss: 0.9503 - accuracy: 0.5000

19/19 [==============================] - 0s 3ms/step - loss: 1.0555 - accuracy: 0.6040


Epoch 15/15
 1/19 [>.............................] - ETA: 0s - loss: 0.7961 - accuracy: 0.6250

19/19 [==============================] - 0s 3ms/step - loss: 0.9436 - accuracy: 0.6535
